apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-keycloak-pv-claim
  labels:
    app: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi