version: '3.9'
services:
  rentalapp:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - rentalapp-mysql
      - rentalapp-redis
    networks:
      - rental-journey
  
  rentalapp-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: rentalapp
      MYSQL_ROOT_PASSWORD: root
    networks:
      - rental-journey

  rentalapp-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rentalapp
    networks:
      - rental-journey
  
  rentalapp-redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - rental-journey

networks:
  rental-journey:
    name: network-journey
    external: true