apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-app

  template:
    metadata:
      labels:
        app: keycloak-app
    spec:
      containers:
      - name: jornada-keycloak
        image: quay.io/keycloak/keycloak:21.1
        args: ["start-dev"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: keycloak-app-conf
        env:
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-mysql-pass
              key: password
